/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { TsoaMapStory } from './tsoaMapStory';
import type { GetStory200AllOf } from './getStory200AllOf';

export type GetStory200 = TsoaMapStory & GetStory200AllOf;
