/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type N24EnumsStorySectionType = typeof N24EnumsStorySectionType[keyof typeof N24EnumsStorySectionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const N24EnumsStorySectionType = {
  STORY: 'STORY',
  CHOICE: 'CHOICE',
} as const;
