/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { StoryWithChoices } from './storyWithChoices';
import type { StartStory201AllOf } from './startStory201AllOf';

export type StartStory201 = StoryWithChoices & StartStory201AllOf;
