/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { StoryWithChoicesChoicesItem } from './storyWithChoicesChoicesItem';

export interface StoryWithChoices {
  choices: StoryWithChoicesChoicesItem[];
  story: string;
}
