/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type StoryWithChoicesChoicesItemType = typeof StoryWithChoicesChoicesItemType[keyof typeof StoryWithChoicesChoicesItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoryWithChoicesChoicesItemType = {
  active: 'active',
  passive: 'passive',
  neutral: 'neutral',
} as const;
