/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type StorySectionSchemaAllOfType = typeof StorySectionSchemaAllOfType[keyof typeof StorySectionSchemaAllOfType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorySectionSchemaAllOfType = {
  CHOICE: 'CHOICE',
  STORY: 'STORY',
} as const;
