/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export interface TsoaMapStory {
  id: string;
  title: string;
  content: string | null;
  published: boolean;
  authorId: string;
  createdAt: string;
}
